import type { Exercise } from './types'

// FitShqip V2 — 20 ushtrime të reja për secilën nga 10 kategoritë ekzistuese.
// Skema e pandryshuar ({ name, muscle, instructions }). Bashkohen te EXERCISES në
// lib/exercises.ts, ndaj kërkimi, filtrat, rutinat dhe rekordet funksionojnë automatikisht.
// Rregull: `name` duhet të jetë unik globalisht (përdoret si çelës në rutina/histori/PR).
export const V2_EXERCISES: Exercise[] = [
  // ---------- Gjoks (20) ----------
  { name: 'Decline Bench Press', muscle: 'Gjoks', instructions: 'Shtrihu në stol të pjerrët me kokën poshtë dhe siguro këmbët. Ule shufrën kontrolluar te gjoksi i poshtëm, pastaj shtyje lart. Fokus: pjesa e poshtme e gjoksit.' },
  { name: 'Incline Dumbbell Press', muscle: 'Gjoks', instructions: 'Stoli në 30-45°, dumbellët në nivel të gjoksit të sipërm. Shtyji lart pa i përplasur në krye dhe ulji ngadalë me bërryla nën 45°. Fokus: gjoksi i sipërm.' },
  { name: 'Decline Dumbbell Press', muscle: 'Gjoks', instructions: 'Në stol të pjerrët poshtë, mbaj dumbellët mbi gjoks. Ulji kontrolluar anash gjoksit të poshtëm, pastaj shtyji lart. Fokus: pjesa e poshtme e gjoksit.' },
  { name: 'Smith Machine Bench Press', muscle: 'Gjoks', instructions: 'Shtrihu nën shufrën e Smith machine me sytë nën shufër. Zgjidhe dhe ule te gjoksi me kontroll, pastaj shtyje lart. Fokus: gjoksi me stabilitet më të madh.' },
  { name: 'Machine Chest Press', muscle: 'Gjoks', instructions: 'Ulu me shpinë të mbështetur dhe dorezat në nivel gjoksi. Shtyji përpara pa mbyllur plotësisht bërrylat dhe kthehu ngadalë. Fokus: gjoksi i izoluar dhe i sigurt.' },
  { name: 'Incline Machine Press', muscle: 'Gjoks', instructions: 'Rregullo ulësen që dorezat të jenë pak mbi gjoks. Shtyji lart e përpara me kontroll dhe ktheji ngadalë. Fokus: gjoksi i sipërm.' },
  { name: 'Pec Deck Fly', muscle: 'Gjoks', instructions: 'Ulu me shpinë të mbështetur, krahët pak të përkulur në dorezat. Mbyllji para gjoksit duke shtrydhur muskujt dhe hapi ngadalë. Fokus: izolimi i gjoksit.' },
  { name: 'Cable Crossover', muscle: 'Gjoks', instructions: 'Mes dy kabllove të larta, hidh një hap përpara. Tërhiq dorezat poshtë e brenda deri sa takohen para belit, pastaj hapi ngadalë. Fokus: gjoksi i poshtëm dhe i brendshëm.' },
  { name: 'Low-to-High Cable Fly', muscle: 'Gjoks', instructions: 'Me kabllot poshtë, tërhiq dorezat lart e brenda deri para fytyrës me bërryla të buta. Ktheji ngadalë pa lëkundur trupin. Fokus: gjoksi i sipërm.' },
  { name: 'Incline Dumbbell Fly', muscle: 'Gjoks', instructions: 'Në stol të pjerrët, dumbellët mbi gjoks me bërryla pak të përkulur. Hapi anash në hark deri te shtrirja e rehatshme, pastaj mbyllji. Fokus: shtrirja e gjoksit të sipërm.' },
  { name: 'Dumbbell Pullover', muscle: 'Gjoks', instructions: 'Shtrihu tërthor në stol dhe mbaj një dumbell me dy duar mbi gjoks. Ule prapa kokës në hark me krahë pak të përkulur, pastaj ktheje mbi gjoks. Fokus: gjoksi dhe kafazi i kraharorit.' },
  { name: 'Svend Press', muscle: 'Gjoks', instructions: 'Në këmbë, shtrëngo dy pllaka mes pëllëmbëve para gjoksit. Shtyji përpara duke i shtypur së bashku dhe kthehu ngadalë. Fokus: gjoksi i brendshëm.' },
  { name: 'Floor Press me Dumbbells', muscle: 'Gjoks', instructions: 'Shtrihu në dysheme me dumbellët mbi gjoks. Ule derisa bërrylat prekin dyshemenë lehtë, bëj pauzë të shkurtër dhe shtyji lart. Fokus: gjoksi dhe triceps-i, me shpatulla të mbrojtura.' },
  { name: 'Wide Push Up', muscle: 'Gjoks', instructions: 'Duart më gjerë se supet, trupi drejt si dërrasë. Ule gjoksin drejt dyshemesë me kontroll dhe shtyje lart. Fokus: gjoksi i jashtëm.' },
  { name: 'Decline Push Up', muscle: 'Gjoks', instructions: 'Këmbët mbi stol, duart në dysheme sa supet. Ule gjoksin drejt dyshemesë me bark të shtrënguar dhe shtyje lart. Fokus: gjoksi i sipërm dhe shpatullat e përparme.' },
  { name: 'Incline Push Up', muscle: 'Gjoks', instructions: 'Duart mbi stol ose shufër të ngritur, trupi drejt. Ule gjoksin drejt stolit dhe shtyje lart. Version më i lehtë për fillestarët. Fokus: gjoksi i poshtëm.' },
  { name: 'Archer Push Up', muscle: 'Gjoks', instructions: 'Me duar shumë të gjera, ule trupin drejt njërës dorë duke mbajtur krahun tjetër të shtrirë. Shtyje lart dhe ndërro anën. Version i avancuar. Fokus: gjoksi me ngarkesë njëanshme.' },
  { name: 'Band Chest Press', muscle: 'Gjoks', instructions: 'Kalo elastikun pas shpinës dhe mbaji skajet në duar. Shtyji përpara derisa krahët drejtohen dhe ktheji ngadalë kundër rezistencës. Fokus: gjoksi, ideal për shtëpi.' },
  { name: 'Cable Chest Press', muscle: 'Gjoks', instructions: 'Mes dy kabllove në nivel gjoksi, shtyji dorezat përpara me trup të qëndrueshëm. Mbyllji pranë njëri-tjetrit dhe kthehu ngadalë. Fokus: gjoksi me tension të vazhdueshëm.' },
  { name: 'Chest Dips', muscle: 'Gjoks', instructions: 'Në shufra paralele, përkul trupin pak përpara. Ule trupin derisa bërrylat të jenë rreth 90°, pastaj shtyje lart. Fokus: pjesa e poshtme e gjoksit.' },

  // ---------- Shpinë (20) ----------
  { name: 'T-Bar Row', muscle: 'Shpinë', instructions: 'Kap dorezën e T-bar, gjunjët pak të përkulur dhe shpinën drejt. Tërhiq peshën drejt barkut duke shtrënguar shpatullat dhe ule kontrolluar. Fokus: trashësia e shpinës së mesme.' },
  { name: 'One-Arm Dumbbell Row', muscle: 'Shpinë', instructions: 'Mbështet një dorë dhe një gju në stol, shpina paralele me dyshemenë. Tërhiq dumbellin drejt ijes, mbaj një sekondë dhe ule ngadalë. Fokus: latissimus-i njëanshëm.' },
  { name: 'Chest-Supported Row', muscle: 'Shpinë', instructions: 'Shtrihu me gjoks në stol të pjerrët, dumbellët varur poshtë. Tërhiq bërrylat prapa duke shtrydhur shpatullat dhe ulji ngadalë. Fokus: shpina e mesme pa ngarkesë në shpinën e poshtme.' },
  { name: 'Pendlay Row', muscle: 'Shpinë', instructions: 'Shufra në dysheme, shpina paralele me të. Tërhiq shufrën shpejt te barku i sipërm pa lëvizur shpinën dhe ule në dysheme çdo përsëritje. Fokus: fuqia e shpinës.' },
  { name: 'Meadows Row', muscle: 'Shpinë', instructions: 'Vendos shufrën në landmine dhe qëndro anash saj. Kap skajin me një dorë dhe tërhiq drejt ijes me bërryl të lartë, ule kontrolluar. Fokus: shpina e sipërme dhe latissimus-i.' },
  { name: 'Inverted Row', muscle: 'Shpinë', instructions: 'Shtrihu poshtë një shufre të ulët dhe kap me duar sa supet. Mbaj trupin drejt, tërhiq gjoksin drejt shufrës dhe ule ngadalë. Fokus: shpina me peshën e trupit.' },
  { name: 'Straight-Arm Pulldown', muscle: 'Shpinë', instructions: 'Në kabllon e lartë me krahë pothuaj të drejtë, përkul trupin lehtë. Tërhiq shufrën poshtë deri te kofshët në hark dhe kthehu ngadalë. Fokus: izolimi i latissimus-it.' },
  { name: 'Close-Grip Lat Pulldown', muscle: 'Shpinë', instructions: 'Me dorezë V ose kapje të ngushtë, tërhiq drejt gjoksit të sipërm me bërryla pranë trupit. Lëshoje ngadalë deri te shtrirja. Fokus: pjesa e poshtme e latissimus-it.' },
  { name: 'Reverse-Grip Lat Pulldown', muscle: 'Shpinë', instructions: 'Kap shufrën me pëllëmbë nga ti, sa gjerësia e supeve. Tërhiq drejt gjoksit duke ulur bërrylat dhe kthehu kontrolluar. Fokus: latissimus-i me përfshirje të biceps-it.' },
  { name: 'Single-Arm Cable Row', muscle: 'Shpinë', instructions: 'Ulu para kabllos dhe kap dorezën me një dorë. Tërhiq drejt belit me shpinë të drejtë pa u rrotulluar dhe lëshoje ngadalë. Fokus: shpina njëanshëm, korrigjon pabarazitë.' },
  { name: 'Machine Row', muscle: 'Shpinë', instructions: 'Ulu me gjoks të mbështetur dhe kap dorezat. Tërhiq bërrylat prapa duke shtrydhur shpatullat dhe kthehu ngadalë. Fokus: shpina e mesme.' },
  { name: 'Smith Machine Row', muscle: 'Shpinë', instructions: 'Qëndro e përkulur nga ijet me shufrën e Smith machine. Tërhiq drejt barkut të poshtëm dhe ule kontrolluar, me shpinë neutrale. Fokus: shpina me lëvizje të udhëzuar.' },
  { name: 'Rack Pull', muscle: 'Shpinë', instructions: 'Vendos shufrën në rack në nivel gjuri. Me shpinë drejt, ngrihu duke drejtuar ijet dhe shtrënguar shpatullat, pastaj ule ngadalë. Fokus: shpina e sipërme dhe kapja.' },
  { name: 'Good Morning', muscle: 'Shpinë', instructions: 'Shufra mbi trapez, gjunjët pak të përkulur. Përkul trupin përpara nga ijet me shpinë drejt deri sa ndjen shtrirjen te hamstring-et, pastaj ngrihu. Përdor peshë të lehtë. Fokus: shpina e poshtme.' },
  { name: 'Back Extension', muscle: 'Shpinë', instructions: 'Në stolin e shtrirjes, ijet mbi jastëk. Ule trupin në hark të kontrolluar dhe ngrije deri në vijë të drejtë, jo më lart. Fokus: shpina e poshtme dhe gluteus-i.' },
  { name: 'Chin Up', muscle: 'Shpinë', instructions: 'Kap shufrën me pëllëmbë nga ti, sa supet. Tërhiq trupin lart derisa mjekra kalon shufrën dhe ule ngadalë deri te shtrirja e plotë. Fokus: shpina dhe biceps-i.' },
  { name: 'Neutral-Grip Pull Up', muscle: 'Shpinë', instructions: 'Kap dorezat paralele me pëllëmbët përballë. Tërhiq lart me gjoksin drejt dorezave dhe ule kontrolluar. Fokus: latissimus-i me më pak stres te kyçet.' },
  { name: 'Superman Hold', muscle: 'Shpinë', instructions: 'Shtrihu përmbys me krahë dhe këmbë të shtrira. Ngri njëkohësisht krahët dhe këmbët pak nga dyshemeja, mbaj 2-3 sekonda dhe ule ngadalë. Fokus: shtrirësit e shpinës.' },
  { name: 'Sumo Deadlift', muscle: 'Shpinë', instructions: 'Këmbët shumë gjerë me majat jashtë, duart brenda këmbëve. Ngrije shufrën duke shtyrë dyshemenë dhe duke drejtuar ijet, me shpinë drejt. Fokus: shpina dhe kofshët e brendshme.' },
  { name: 'Resistance Band Row', muscle: 'Shpinë', instructions: 'Ulu me këmbët e shtrira dhe elastikun rreth tyre. Tërhiq dorezat drejt barkut duke shtrënguar shpatullat dhe lëshoji ngadalë. Fokus: shpina, ideal për shtëpi.' },

  // ---------- Shpatulla (20) ----------
  { name: 'Dumbbell Shoulder Press', muscle: 'Shpatulla', instructions: 'Ulur ose në këmbë, mbaj dumbellët në nivel të veshëve. Shtyji lart derisa krahët drejtohen pa u përplasur dhe ulji kontrolluar. Fokus: shpatullat e përparme dhe të mesme.' },
  { name: 'Arnold Press', muscle: 'Shpatulla', instructions: 'Fillo me dumbellët para gjoksit dhe pëllëmbët nga ti. Shtyji lart duke rrotulluar pëllëmbët përpara dhe ktheji ngadalë. Fokus: të gjitha kokat e shpatullës.' },
  { name: 'Military Press', muscle: 'Shpatulla', instructions: 'Në këmbë me këmbët së bashku, shtyje shufrën nga gjoksi lart pa u përkulur prapa. Mbaj barkun dhe gluteus-in të shtrënguar. Fokus: shpatullat e përparme dhe forca.' },
  { name: 'Smith Machine Shoulder Press', muscle: 'Shpatulla', instructions: 'Ulu nën shufrën e Smith machine dhe kap pak më gjerë se supet. Shtyje lart dhe ule te mjekra me kontroll. Fokus: shpatullat me stabilitet.' },
  { name: 'Machine Shoulder Press', muscle: 'Shpatulla', instructions: 'Rregullo ulësen që dorezat të jenë në nivel shpatullash. Shtyji lart deri sa krahët drejtohen dhe kthehu ngadalë. Fokus: shpatullat, e sigurt për seri të rënda.' },
  { name: 'Cable Lateral Raise', muscle: 'Shpatulla', instructions: 'Qëndro anash kabllos së ulët dhe kap dorezën me dorën e largët. Ngrije anash deri në nivelin e supit dhe ule ngadalë. Fokus: shpatulla e mesme me tension të vazhdueshëm.' },
  { name: 'Leaning Lateral Raise', muscle: 'Shpatulla', instructions: 'Mbahu me një dorë dhe anohu anash, me dumbell në dorën tjetër. Ngrije anash deri në nivel supi dhe ule ngadalë. Fokus: shpatulla e mesme me shtrirje më të madhe.' },
  { name: 'Bent-Over Rear Delt Raise', muscle: 'Shpatulla', instructions: 'Përkul trupin përpara nga ijet me dumbellët varur. Hapi anash deri në nivel shpatullash duke shtrënguar shpinën e sipërme dhe ulji kontrolluar. Fokus: shpatulla e pasme.' },
  { name: 'Reverse Pec Deck', muscle: 'Shpatulla', instructions: 'Ulu me gjoksin kundër jastëkut dhe kap dorezat. Hapi prapa në hark me bërryla të buta dhe kthehu ngadalë. Fokus: shpatulla e pasme dhe shpina e sipërme.' },
  { name: 'Cable Rear Delt Fly', muscle: 'Shpatulla', instructions: 'Me kabllo të kryqëzuara, kap dorezat dhe hapi krahët anash e prapa në nivel supesh. Kthehu ngadalë. Fokus: shpatulla e pasme.' },
  { name: 'Upright Row', muscle: 'Shpatulla', instructions: 'Kap shufrën me duar sa supet dhe ngrije drejt gjoksit të sipërm me bërryla më lart se duart, jo mbi nivelin e supeve. Ule ngadalë. Fokus: shpatullat e mesme dhe trapezi.' },
  { name: 'Cable Front Raise', muscle: 'Shpatulla', instructions: 'Me kabllon e ulët mes këmbëve, ngrije dorezën përpara deri në nivel supi me krah të drejtë dhe ule ngadalë. Fokus: shpatulla e përparme.' },
  { name: 'Plate Front Raise', muscle: 'Shpatulla', instructions: 'Mbaj një pllakë me dy duar. Ngrije përpara deri në nivel të syve me krahë të drejtë dhe ule kontrolluar. Fokus: shpatullat e përparme.' },
  { name: 'Push Press', muscle: 'Shpatulla', instructions: 'Shufra në gjoks, këmbët sa supet. Përkul pak gjunjët dhe shtyje menjëherë lart, duke e mbyllur lëvizjen me krahë mbi kokë. Ule ngadalë. Fokus: fuqia e shpatullave.' },
  { name: 'Landmine Shoulder Press', muscle: 'Shpatulla', instructions: 'Mbaj skajin e shufrës landmine në nivel supi me një dorë. Shtyje diagonalisht lart deri sa krahu drejtohet dhe ule ngadalë. Fokus: shpatulla me ngarkesë më të butë për kyçin.' },
  { name: 'Pike Push Up', muscle: 'Shpatulla', instructions: 'Në pozicion V të përmbysur, me ijet lart dhe duart në dysheme. Ule kokën drejt dyshemesë duke përkulur bërrylat dhe shtyje lart. Fokus: shpatullat me peshën e trupit.' },
  { name: 'Band Pull Apart', muscle: 'Shpatulla', instructions: 'Mbaj elastikun me krahë të shtrirë para gjoksit. Hapi anash duke shtrënguar shpatullat dhe kthehu ngadalë. Fokus: shpatulla e pasme dhe qëndrueshmëria e shpatullave.' },
  { name: 'Y Raise', muscle: 'Shpatulla', instructions: 'Shtrihu përmbys në stol të pjerrët me dumbell të lehtë. Ngri krahët lart në formë Y me gishtat e mëdhenj lart dhe ulji ngadalë. Fokus: shpatulla e pasme dhe trapezi i poshtëm.' },
  { name: 'Kettlebell Shoulder Press', muscle: 'Shpatulla', instructions: 'Mbaj kettlebell-in në pozicion rack te supi. Shtyje lart derisa krahu drejtohet dhe ule kontrolluar. Fokus: shpatulla dhe stabiliteti i bërthamës.' },
  { name: 'Cuban Press', muscle: 'Shpatulla', instructions: 'Me dumbell të lehtë, tërhiq bërrylat lart në nivel supi, rrotulloji parakrahët lart, pastaj shtyji mbi kokë dhe kthehu ngadalë. Fokus: rrotatorët e shpatullës.' },

  // ---------- Biceps (20) ----------
  { name: 'EZ-Bar Curl', muscle: 'Biceps', instructions: 'Kap shufrën EZ në pjesët e përkulura, me bërryla pranë trupit. Përkul krahët lart duke shtrënguar biceps-in dhe ule ngadalë. Fokus: biceps me më pak stres te kyçet.' },
  { name: 'Preacher Curl', muscle: 'Biceps', instructions: 'Mbështet krahët mbi jastëkun e preacher-it. Përkul shufrën lart dhe ule ngadalë deri te shtrirja pothuaj e plotë. Fokus: biceps pa mashtrim me trupin.' },
  { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', instructions: 'Mbështet një krah mbi jastëkun e pjerrët me dumbell në dorë. Përkule lart dhe ule ngadalë deri te shtrirja. Fokus: biceps njëanshëm.' },
  { name: 'Machine Preacher Curl', muscle: 'Biceps', instructions: 'Rregullo ulësen që supet të jenë mbi jastëk. Përkul dorezat lart dhe ule me kontroll pa i hedhur peshat. Fokus: biceps me tension të vazhdueshëm.' },
  { name: 'Incline Dumbbell Curl', muscle: 'Biceps', instructions: 'Ulu në stol të pjerrët 45°, me krahët varur pas trupit. Përkul dumbellët lart pa lëvizur bërrylat përpara dhe ulji ngadalë. Fokus: koka e gjatë e biceps-it.' },
  { name: 'Concentration Curl', muscle: 'Biceps', instructions: 'Ulu dhe mbështet bërrylin në pjesën e brendshme të kofshës. Përkul dumbellin lart me shtrëngim në krye dhe ule ngadalë. Fokus: biceps i izoluar.' },
  { name: 'Cable Curl', muscle: 'Biceps', instructions: 'Përballë kabllos së ulët me shufër të drejtë, mbaj bërrylat pranë trupit. Përkul lart dhe ule ngadalë. Fokus: biceps me tension të vazhdueshëm.' },
  { name: 'Single-Arm Cable Curl', muscle: 'Biceps', instructions: 'Qëndro anash kabllos së ulët dhe kap dorezën me një dorë. Përkule lart pa lëkundur trupin dhe ule ngadalë. Fokus: biceps njëanshëm.' },
  { name: 'Bayesian Curl', muscle: 'Biceps', instructions: 'Kthe shpinën kabllos së ulët, me krahun pak pas trupit. Përkule dorezën lart duke mbajtur bërrylin prapa dhe ule ngadalë. Fokus: shtrirja e biceps-it.' },
  { name: 'Spider Curl', muscle: 'Biceps', instructions: 'Shtrihu me gjoks mbi stol të pjerrët dhe krahët varur drejt poshtë. Përkul dumbellët lart me bërryla të palëvizshëm dhe ulji ngadalë. Fokus: biceps pa mashtrim.' },
  { name: 'Zottman Curl', muscle: 'Biceps', instructions: 'Përkul dumbellët lart me pëllëmbë nga ti. Në krye rrotulloji pëllëmbët poshtë dhe ulji ngadalë. Fokus: biceps dhe parakrahu.' },
  { name: 'Cross-Body Hammer Curl', muscle: 'Biceps', instructions: 'Me dumbellët neutral, përkul njërin përtej gjoksit drejt shpatullës së kundërt dhe ule ngadalë. Ndërro krahun. Fokus: brachialis dhe biceps.' },
  { name: 'Rope Hammer Curl', muscle: 'Biceps', instructions: 'Në kabllon e ulët me litar, kap me pëllëmbë neutrale. Përkul lart duke hapur litarin në krye dhe ule ngadalë. Fokus: brachialis dhe parakrahu.' },
  { name: 'Drag Curl', muscle: 'Biceps', instructions: 'Me shufër, tërhiq bërrylat prapa dhe ngrije shufrën afër trupit deri te gjoksi. Ule ngadalë pa lëvizur shpinën. Fokus: koka e gjatë e biceps-it.' },
  { name: 'Resistance Band Curl', muscle: 'Biceps', instructions: 'Qëndro mbi elastik me këmbët dhe kap skajet. Përkul krahët lart kundër rezistencës dhe lëshoji ngadalë. Fokus: biceps, ideal për shtëpi.' },
  { name: 'Seated Alternating Curl', muscle: 'Biceps', instructions: 'Ulu drejt me dumbell në çdo dorë. Përkul një krah duke rrotulluar pëllëmbën lart, ule dhe ndërro. Mbaj trupin të palëvizshëm. Fokus: biceps me kontroll.' },
  { name: 'Lying Cable Curl', muscle: 'Biceps', instructions: 'Shtrihu në dysheme me kokën drejt kabllos së ulët. Përkul dorezën drejt ballit me bërryla fiks dhe ule ngadalë. Fokus: shtrëngimi i biceps-it.' },
  { name: 'Waiter Curl', muscle: 'Biceps', instructions: 'Mbaj një dumbell vertikalisht me të dy duart nën kokën e tij. Përkule lart si tabaka dhe ule ngadalë. Fokus: biceps i brendshëm.' },
  { name: '21s Curl', muscle: 'Biceps', instructions: 'Me shufër, bëj 7 përsëritje në gjysmën e poshtme, 7 në gjysmën e sipërme dhe 7 të plota pa pauzë. Përdor peshë të lehtë. Fokus: biceps dhe qëndrueshmëria.' },
  { name: 'High Cable Curl', muscle: 'Biceps', instructions: 'Mes dy kabllove të larta, me krahët anash në nivel supesh. Përkul dorezat drejt kokës duke shtrënguar biceps-in dhe hapi ngadalë. Fokus: kulmi i biceps-it.' },

  // ---------- Triceps (20) ----------
  { name: 'Close-Grip Bench Press', muscle: 'Triceps', instructions: 'Shtrihu në stol dhe kap shufrën sa gjerësia e supeve. Ule te gjoksi i poshtëm me bërryla pranë trupit dhe shtyje lart. Fokus: triceps dhe gjoks.' },
  { name: 'Overhead Dumbbell Extension', muscle: 'Triceps', instructions: 'Mbaj një dumbell me dy duar mbi kokë. Përkul bërrylat duke ulur peshën pas kokës dhe drejtoji ngadalë, me bërryla pranë veshëve. Fokus: koka e gjatë e triceps-it.' },
  { name: 'Overhead Cable Extension', muscle: 'Triceps', instructions: 'Me kabllon e ulët dhe shpinën nga makina, kap litarin mbi kokë. Drejto krahët përpara e lart dhe kthehu ngadalë. Fokus: koka e gjatë e triceps-it.' },
  { name: 'Single-Arm Overhead Extension', muscle: 'Triceps', instructions: 'Mbaj një dumbell me një dorë mbi kokë. Ule pas kokës duke përkulur vetëm bërrylin dhe drejtoje lart. Fokus: triceps njëanshëm.' },
  { name: 'Incline Skull Crusher', muscle: 'Triceps', instructions: 'Në stol të pjerrët, ule shufrën EZ drejt ballit duke përkulur vetëm bërrylat dhe drejtoje lart. Fokus: koka e gjatë e triceps-it.' },
  { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', instructions: 'Shtrihu me dumbell në çdo dorë mbi gjoks. Përkul bërrylat që dumbellët të shkojnë anash kokës dhe drejtoji ngadalë. Fokus: triceps me lëvizje më të lirë.' },
  { name: 'Bench Dips', muscle: 'Triceps', instructions: 'Mbështet duart pas teje në stol me këmbët përpara. Ule trupin duke përkulur bërrylat deri 90° dhe shtyje lart. Fokus: triceps me peshën e trupit.' },
  { name: 'Diamond Push Up', muscle: 'Triceps', instructions: 'Duart bashkë nën gjoks në formë diamanti. Ule gjoksin drejt duarve me bërryla pranë trupit dhe shtyje lart. Fokus: triceps dhe gjoks i brendshëm.' },
  { name: 'JM Press', muscle: 'Triceps', instructions: 'Shtrihu në stol me shufër në duar sa supet. Ule shufrën drejt fytit duke përkulur bërrylat dhe shtyje lart. Përdor peshë të moderuar. Fokus: triceps.' },
  { name: 'Tate Press', muscle: 'Triceps', instructions: 'Shtrihu në stol me dumbell në çdo dorë. Ule dumbellët drejt gjoksit duke hapur bërrylat dhe drejtoji lart. Fokus: izolimi i triceps-it.' },
  { name: 'Dumbbell Kickback', muscle: 'Triceps', instructions: 'Përkul trupin përpara me bërrylin lart pranë trupit. Drejto krahun prapa deri sa të jetë i shtrirë dhe kthehu ngadalë. Fokus: shtrëngimi i triceps-it.' },
  { name: 'Cable Kickback', muscle: 'Triceps', instructions: 'Përkul trupin përpara dhe kap dorezën e kabllos së ulët. Drejto krahun prapa dhe kthehu ngadalë me bërryl fiks. Fokus: triceps me tension të vazhdueshëm.' },
  { name: 'Single-Arm Pushdown', muscle: 'Triceps', instructions: 'Në kabllon e lartë, kap dorezën me një dorë. Shtyje poshtë duke drejtuar krahun dhe kthehu ngadalë, me bërrylin pranë trupit. Fokus: triceps njëanshëm.' },
  { name: 'Reverse-Grip Pushdown', muscle: 'Triceps', instructions: 'Kap shufrën me pëllëmbë lart dhe bërryla pranë trupit. Shtyje poshtë derisa krahët drejtohen dhe kthehu ngadalë. Fokus: koka mediale e triceps-it.' },
  { name: 'V-Bar Pushdown', muscle: 'Triceps', instructions: 'Me dorezë V në kabllon e lartë, shtyje poshtë me bërryla fiks. Drejto krahët plotësisht dhe kthehu ngadalë. Fokus: triceps me kapje të ngushtë.' },
  { name: 'Straight-Bar Pushdown', muscle: 'Triceps', instructions: 'Me shufër të drejtë, shtyje poshtë derisa krahët drejtohen, shtrëngo triceps-in dhe kthehu ngadalë me bërryla pranë trupit. Fokus: të tre kokat e triceps-it.' },
  { name: 'Band Pushdown', muscle: 'Triceps', instructions: 'Fikso elastikun lart dhe tërhiqe poshtë duke drejtuar krahët me bërryla pranë trupit. Kthehu ngadalë. Fokus: triceps, ideal për shtëpi.' },
  { name: 'Smith Machine Close-Grip Press', muscle: 'Triceps', instructions: 'Shtrihu nën shufrën e Smith machine me duar sa supet. Ule te gjoksi i poshtëm dhe shtyje lart me bërryla pranë trupit. Fokus: triceps me stabilitet.' },
  { name: 'Machine Triceps Extension', muscle: 'Triceps', instructions: 'Ulu me krahët mbi jastëk dhe kap dorezat. Drejto krahët poshtë ose përpara dhe kthehu me kontroll. Fokus: triceps i izoluar.' },
  { name: 'Lying Cable Extension', muscle: 'Triceps', instructions: 'Shtrihu përballë kabllos së ulët dhe kap litarin. Drejto krahët lart me bërryla fiks dhe ule ngadalë drejt ballit. Fokus: triceps me tension të vazhdueshëm.' },

  // ---------- Këmbë (20) ----------
  { name: 'Front Squat', muscle: 'Këmbë', instructions: 'Shufra mbi shpatullat e përparme, bërrylat lart. Ulu me gjoks të drejtë deri sa kofshët janë paralele dhe ngrihu duke shtyrë dyshemenë. Fokus: kuadriceps dhe bërthama.' },
  { name: 'Goblet Squat', muscle: 'Këmbë', instructions: 'Mbaj një dumbell ose kettlebell para gjoksit. Ulu thellë me gjoks lart dhe bërryla brenda gjunjëve, pastaj ngrihu me kontroll. Fokus: kuadriceps dhe lëvizshmëria.' },
  { name: 'Bulgarian Split Squat', muscle: 'Këmbë', instructions: 'Vendos këmbën e pasme mbi stol dhe hidh një hap të gjerë përpara. Ule gjurin e pasmë drejt dyshemesë dhe ngrihu duke shtyrë me këmbën përpara. Fokus: kuadriceps dhe gluteus njëanshëm.' },
  { name: 'Hack Squat', muscle: 'Këmbë', instructions: 'Mbështet shpinën në makinë dhe këmbët në platformë sa supet. Ulu deri sa kofshët janë paralele dhe shtyje lart pa mbyllur gjunjët. Fokus: kuadriceps.' },
  { name: 'Smith Machine Squat', muscle: 'Këmbë', instructions: 'Shufra mbi trapez dhe këmbët pak para trupit. Ulu deri në paralele dhe ngrihu me kontroll. Fokus: kuadriceps me stabilitet më të madh.' },
  { name: 'Leg Extension', muscle: 'Këmbë', instructions: 'Ulu në makinë me jastëkun mbi kyçet e këmbëve. Drejto këmbët derisa gjunjët janë pothuaj të shtrirë dhe ulji ngadalë. Fokus: izolimi i kuadricepsit.' },
  { name: 'Walking Lunges', muscle: 'Këmbë', instructions: 'Hidh një hap përpara dhe ule gjurin e pasmë drejt dyshemesë, pastaj hidh hapin tjetër duke ecur përpara. Mbaj shpinën drejt. Fokus: kuadriceps dhe gluteus.' },
  { name: 'Reverse Lunge', muscle: 'Këmbë', instructions: 'Hidh një hap prapa dhe ule gjurin e pasmë drejt dyshemesë, pastaj kthehu në fillim. Gjuri përpara mbetet mbi kyçin. Fokus: gluteus dhe kuadriceps me më pak stres te gjuri.' },
  { name: 'Step Up', muscle: 'Këmbë', instructions: 'Vendos një këmbë mbi stol ose platformë. Shtyje trupin lart me atë këmbë dhe ule ngadalë, pa u ndihmuar nga këmba tjetër. Fokus: kuadriceps dhe gluteus.' },
  { name: 'Hip Thrust', muscle: 'Këmbë', instructions: 'Shpatullat e sipërme mbi stol dhe shufra mbi ije. Shtyje ijet lart duke shtrënguar gluteus-in dhe ule ngadalë. Fokus: gluteus.' },
  { name: 'Glute Bridge', muscle: 'Këmbë', instructions: 'Shtrihu përmbys me gjunjë të përkulur dhe këmbët në dysheme. Ngri ijet derisa trupi është drejt, shtrëngo gluteus-in dhe ule ngadalë. Fokus: gluteus dhe hamstring.' },
  { name: 'Stiff-Leg Deadlift', muscle: 'Këmbë', instructions: 'Me gjunjë pothuaj të shtrirë, ule shufrën përgjatë këmbëve me shpinë drejt. Ngrihu duke shtyrë ijet përpara. Fokus: hamstring dhe gluteus.' },
  { name: 'Seated Leg Curl', muscle: 'Këmbë', instructions: 'Ulu në makinë me jastëkun mbi kyçet. Përkul këmbët poshtë e prapa dhe ktheji ngadalë. Fokus: hamstring me tension të vazhdueshëm.' },
  { name: 'Lying Leg Curl', muscle: 'Këmbë', instructions: 'Shtrihu përmbys në makinë me jastëkun mbi kyçet. Përkul këmbët drejt gluteus-it dhe ule ngadalë. Fokus: hamstring.' },
  { name: 'Seated Calf Raise', muscle: 'Këmbë', instructions: 'Ulu me gjunjë të përkulur dhe jastëk mbi kofshë. Ngrihu në majë të gishtave dhe ule ngadalë deri te shtrirja e plotë. Fokus: soleus i pulpës.' },
  { name: 'Kettlebell Swing', muscle: 'Këmbë', instructions: 'Këmbët gjerë dhe kettlebell mes tyre. Shtyje ijet përpara fuqishëm për ta hedhur kettlebell-in deri në nivel gjoksi dhe lëre të kthehet me kontroll. Fokus: gluteus dhe hamstring.' },
  { name: 'Cable Pull Through', muscle: 'Këmbë', instructions: 'Kthe shpinën kabllos së ulët dhe kap litarin mes këmbëve. Përkul ijet prapa dhe shtyji përpara duke shtrënguar gluteus-in. Fokus: gluteus dhe hamstring.' },
  { name: 'Sumo Squat', muscle: 'Këmbë', instructions: 'Këmbët shumë gjerë me majat jashtë. Ulu thellë me gjoks lart duke mbajtur një dumbell mes këmbëve dhe ngrihu. Fokus: kofshët e brendshme dhe gluteus-i.' },
  { name: 'Wall Sit', muscle: 'Këmbë', instructions: 'Mbështet shpinën pas murit dhe ulu derisa kofshët paralele me dyshemenë. Mbaje pozicionin pa ndihmën e duarve. Regjistro sekondat si përsëritje. Fokus: qëndrueshmëria e kuadricepsit.' },
  { name: 'Bodyweight Squat', muscle: 'Këmbë', instructions: 'Këmbët sa supet dhe duart përpara. Ulu duke shtyrë ijet prapa me gjoks lart dhe ngrihu me kontroll. Fokus: kuadriceps dhe gluteus, bazë për fillestarët.' },

  // ---------- Bark (20) ----------
  { name: 'Cable Crunch', muscle: 'Bark', instructions: 'Gjunjëzohu para kabllos së lartë me litarin pas kokës. Përkul bustin poshtë duke shtrënguar barkun dhe kthehu ngadalë, pa tërhequr me krahë. Fokus: rectus abdominis.' },
  { name: 'Bicycle Crunch', muscle: 'Bark', instructions: 'Shtrihu me duar pas kokës. Çoje bërrylin drejt gjurit të kundërt duke zgjatur këmbën tjetër dhe ndërro në mënyrë të kontrolluar. Fokus: barku dhe oblikët.' },
  { name: 'Russian Twist', muscle: 'Bark', instructions: 'Ulu me këmbët pak të ngritura dhe trupin të pjerrët. Rrotullo bustin majtas e djathtas duke prekur anët. Fokus: oblikët.' },
  { name: 'Lying Leg Raise', muscle: 'Bark', instructions: 'Shtrihu me duar nën ije dhe këmbë të shtrira. Ngri këmbët deri në 90° dhe ulji ngadalë pa i prekur dyshemenë. Fokus: barku i poshtëm.' },
  { name: 'Reverse Crunch', muscle: 'Bark', instructions: 'Shtrihu me gjunjë të përkulur në ajër. Ngri ijet nga dyshemeja duke tërhequr gjunjët drejt gjoksit dhe ulji ngadalë. Fokus: barku i poshtëm.' },
  { name: 'Ab Wheel Rollout', muscle: 'Bark', instructions: 'Gjunjëzohu me rrotën e barkut në duar. Shtyje përpara me shpinë të drejtë dhe bark të shtrënguar, pastaj kthehu. Fillo me hapësirë të kufizuar. Fokus: bërthama.' },
  { name: 'Mountain Climber', muscle: 'Bark', instructions: 'Në pozicion shtytjeje, tërhiq gjunjët drejt gjoksit me radhë në ritëm të kontrolluar. Mbaj ijet të ulëta. Fokus: barku dhe kardio.' },
  { name: 'Dead Bug', muscle: 'Bark', instructions: 'Shtrihu me krahë lart dhe gjunjë në 90°. Zgjat krahun dhe këmbën e kundërt ngadalë, duke mbajtur shpinën kundër dyshemesë. Fokus: stabiliteti i bërthamës.' },
  { name: 'Bird Dog', muscle: 'Bark', instructions: 'Në katër këmbë, zgjat krahun e djathtë dhe këmbën e majtë njëkohësisht, mbaj një sekondë dhe ndërro. Shpina neutrale. Fokus: bërthama dhe balanca.' },
  { name: 'Side Plank', muscle: 'Bark', instructions: 'Mbështetu në një bërryl dhe anën e këmbës, me ijet lart në vijë të drejtë. Mbaje pozicionin dhe ndërro anën. Regjistro sekondat. Fokus: oblikët.' },
  { name: 'Hollow Body Hold', muscle: 'Bark', instructions: 'Shtrihu dhe ngri krahët e këmbët pak nga dyshemeja, duke mbajtur shpinën e poshtme në dysheme. Mbaje pozicionin. Regjistro sekondat. Fokus: bërthama.' },
  { name: 'V-Up', muscle: 'Bark', instructions: 'Shtrihu me krahë lart. Ngri njëkohësisht bustin dhe këmbët për të prekur gishtat në formë V dhe ule ngadalë. Fokus: barku i sipërm dhe i poshtëm.' },
  { name: 'Flutter Kicks', muscle: 'Bark', instructions: 'Shtrihu me duar nën ije dhe këmbët pak mbi dysheme. Ngri dhe ule këmbët në lëvizje të vogla alternative. Fokus: barku i poshtëm.' },
  { name: 'Cable Woodchopper', muscle: 'Bark', instructions: 'Në kabllon e lartë, tërhiq dorezën diagonalisht poshtë përtej trupit duke rrotulluar bustin dhe kthehu ngadalë. Fokus: oblikët dhe rrotullimi.' },
  { name: 'Pallof Press', muscle: 'Bark', instructions: 'Qëndro anash kabllos në nivel gjoksi dhe mbaj dorezën para gjoksit. Shtyje përpara dhe mbaje 2 sekonda pa u rrotulluar, pastaj kthehu. Fokus: anti-rrotullimi i bërthamës.' },
  { name: 'Decline Sit Up', muscle: 'Bark', instructions: 'Në stol të pjerrët me këmbët e siguruara, ngrihu me kontroll deri te ulja dhe ulu ngadalë pa tërhequr qafën. Fokus: barku me rezistencë më të madhe.' },
  { name: 'Sit Up', muscle: 'Bark', instructions: 'Shtrihu me gjunjë të përkulur dhe krahët para gjoksit. Ngrihu deri te ulja duke shtrënguar barkun dhe ulu ngadalë. Fokus: barku dhe fleksorët e ijes.' },
  { name: 'Toe Touch Crunch', muscle: 'Bark', instructions: 'Shtrihu me këmbët drejt lart. Ngri shpatullat dhe zgjat duart drejt gishtave, pastaj ulu ngadalë. Fokus: barku i sipërm.' },
  { name: 'Hanging Knee Raise', muscle: 'Bark', instructions: 'Varur në shufër, tërhiq gjunjët drejt gjoksit pa u lëkundur dhe ulji ngadalë. Version më i lehtë i ngritjes së këmbëve. Fokus: barku i poshtëm.' },
  { name: 'Machine Crunch', muscle: 'Bark', instructions: 'Ulu në makinë me jastëkun para gjoksit. Përkul bustin përpara duke shtrënguar barkun dhe kthehu ngadalë. Fokus: barku me rezistencë të rregullueshme.' },

  // ---------- Kardio (20) ----------
  { name: 'Rowing Machine', muscle: 'Kardio', instructions: 'Ulu me këmbët në mbështetëse. Shtyj me këmbët, pastaj me shpinën dhe tërhiq dorezën te barku; kthehu në të kundërt. Regjistro minutat. Fokus: kardio i trupit të plotë.' },
  { name: 'Elliptical', muscle: 'Kardio', instructions: 'Qëndro në makinë dhe lëviz këmbët e krahët në ritëm të qëndrueshëm me shpinë drejt. Regjistro minutat. Fokus: kardio me ndikim të ulët te kyçet.' },
  { name: 'Stair Climber', muscle: 'Kardio', instructions: 'Ngjitu në shkallët e makinës duke shtypur gjithë shputën, pa u mbështetur te doreza. Regjistro minutat. Fokus: qëndrueshmëria e këmbëve dhe kardio.' },
  { name: 'Incline Treadmill Walk', muscle: 'Kardio', instructions: 'Rrite pjerrësinë e shiritit dhe ec me hapa të plotë pa u kapur te doreza. Regjistro minutat. Fokus: kardio dhe gluteus me ndikim të ulët.' },
  { name: 'Sprint Intervals', muscle: 'Kardio', instructions: 'Vrapo shpejt 20-30 sekonda me intensitet të lartë, pastaj ec ose pusho 60-90 sekonda. Përsërit intervalet dhe regjistro numrin e tyre. Fokus: kapaciteti kardio.' },
  { name: 'Burpees', muscle: 'Kardio', instructions: 'Nga këmbë, ulu, hidh këmbët prapa në shtytje, bëj një push-up, tërhiq këmbët dhe kërce lart. Mbaj ritëm të kontrolluar. Fokus: kardio i trupit të plotë.' },
  { name: 'Jumping Jacks', muscle: 'Kardio', instructions: 'Kërce duke hapur këmbët dhe duke ngritur krahët mbi kokë, pastaj kthehu. Ulu butë mbi majat e këmbëve. Fokus: ngrohje dhe kardio.' },
  { name: 'High Knees', muscle: 'Kardio', instructions: 'Vrapo në vend duke ngritur gjunjët deri në nivel ijesh me ritëm të shpejtë dhe krahë aktivë. Ulu butë. Fokus: kardio dhe fleksorët e ijes.' },
  { name: 'Battle Ropes', muscle: 'Kardio', instructions: 'Me gjunjë pak të përkulur, shkund litarët në mënyrë alternative ose njëkohësisht me valë të shpejta. Regjistro sekondat. Fokus: kardio dhe shpatullat.' },
  { name: 'Box Jump', muscle: 'Kardio', instructions: 'Qëndro para kutisë, përkul pak dhe kërce mbi të duke zbritur butë me të dyja këmbët. Zbrit nga kutia me hap, jo me kërcim. Fokus: fuqia e këmbëve dhe kardio.' },
  { name: 'Swimming', muscle: 'Kardio', instructions: 'Not në stilin që zgjedh me ritëm të qëndrueshëm dhe frymëmarrje të rregullt. Regjistro minutat. Fokus: kardio i trupit të plotë pa ndikim te kyçet.' },
  { name: 'Çiklizëm në Natyrë', muscle: 'Kardio', instructions: 'Pedalo me ritëm të qëndrueshëm, me përkrenare dhe duke respektuar rregullat e trafikut. Rregullo marsin sipas terrenit. Regjistro minutat. Fokus: qëndrueshmëria dhe këmbët.' },
  { name: 'Skater Jumps', muscle: 'Kardio', instructions: 'Kërce anash nga një këmbë në tjetrën me zbritje të butë dhe krahët në balancë. Mbaj gjurin e zbritjes të përkulur. Fokus: kardio dhe stabiliteti i këmbëve.' },
  { name: 'Shadow Boxing', muscle: 'Kardio', instructions: 'Me këmbë të lehta, hidh goditje të kontrolluara në ajër me rrotullim të ijeve dhe lëvizje të kokës. Regjistro raundet. Fokus: kardio dhe koordinimi.' },
  { name: 'Sled Push', muscle: 'Kardio', instructions: 'Me duar në doreza, shtyje sajën përpara me trup të pjerrët dhe hapa të fuqishëm. Regjistro distancën ose seritë. Fokus: kardio dhe këmbët.' },
  { name: 'Assault Bike', muscle: 'Kardio', instructions: 'Ulu dhe pedalo duke shtyrë e tërhequr dorezat. Mbaj ritëm të qëndrueshëm ose bëj intervale. Regjistro minutat. Fokus: kardio me intensitet të lartë.' },
  { name: 'Ecje e Shpejtë', muscle: 'Kardio', instructions: 'Ec me hapa të gjatë dhe krahë që lëvizin, me shpinë drejt. Mbaj ritëm ku mund të flasësh pak. Regjistro minutat. Fokus: kardio me ndikim të ulët.' },
  { name: 'Butt Kicks', muscle: 'Kardio', instructions: 'Vrapo në vend duke tërhequr thembrat drejt gluteus-it me ritëm të shpejtë dhe trup drejt. Ulu butë. Fokus: ngrohje dhe hamstring.' },
  { name: 'Jump Squat', muscle: 'Kardio', instructions: 'Ulu në squat dhe kërce lart eksplozivisht, pastaj ulu butë në squat tjetër. Mbaj gjunjët të drejtuar sipas majave. Fokus: fuqia dhe kardio.' },
  { name: 'Vrapim në Shkallë', muscle: 'Kardio', instructions: 'Vrapo ose ec shpejt shkallëve lart dhe zbrit me hap të qetë. Përsërit seritë dhe regjistro numrin e rrugëve. Fokus: kardio dhe këmbët.' },

  // ---------- Trapez (20) ----------
  { name: 'Smith Machine Shrug', muscle: 'Trapez', instructions: 'Kap shufrën e Smith machine para kofshëve. Ngri supet drejt veshëve pa i rrotulluar, mbaj një sekondë dhe ule ngadalë. Fokus: trapezi i sipërm.' },
  { name: 'Cable Shrug', muscle: 'Trapez', instructions: 'Qëndro para kabllos së ulët me shufër. Ngri supet drejt veshëve, shtrëngo dhe ule ngadalë. Fokus: trapezi me tension të vazhdueshëm.' },
  { name: 'Machine Shrug', muscle: 'Trapez', instructions: 'Kap dorezat e makinës dhe ngri supet drejt veshëve me kontroll, mbaj një sekondë dhe ule ngadalë. Fokus: trapezi i sipërm.' },
  { name: 'Behind-the-Back Shrug', muscle: 'Trapez', instructions: 'Mbaj shufrën pas trupit me duar sa supet. Ngri supet lart, mbaj një sekondë dhe ule ngadalë me shpinë drejt. Fokus: trapezi i mesëm dhe i sipërm.' },
  { name: 'Trap Bar Shrug', muscle: 'Trapez', instructions: 'Qëndro brenda trap bar dhe kap dorezat. Ngri supet lart në vijë të drejtë pa përkulur krahët dhe ule kontrolluar. Fokus: trapezi me ngarkesë të balancuar.' },
  { name: 'Farmer\'s Walk', muscle: 'Trapez', instructions: 'Mbaj një peshë të rëndë në çdo dorë dhe ec me hapa të shkurtër, me shpinë drejt dhe supet pas. Regjistro distancën ose kohën. Fokus: trapezi, kapja dhe bërthama.' },
  { name: 'Incline Dumbbell Shrug', muscle: 'Trapez', instructions: 'Shtrihu me gjoks mbi stol të pjerrët dhe dumbellët varur. Ngri supet drejt veshëve dhe ulji ngadalë. Fokus: trapezi i mesëm pa ngarkesë në shpinë.' },
  { name: 'Kettlebell Shrug', muscle: 'Trapez', instructions: 'Mbaj një kettlebell në çdo dorë me krahët anash. Ngri supet lart, shtrëngo një sekondë dhe ule ngadalë. Fokus: trapezi dhe kapja.' },
  { name: 'Single-Arm Dumbbell Shrug', muscle: 'Trapez', instructions: 'Me një dumbell në njërën dorë, ngri supin drejt veshit pa anuar trupin dhe ule ngadalë. Ndërro krahun. Fokus: trapezi njëanshëm.' },
  { name: 'Dumbbell High Pull', muscle: 'Trapez', instructions: 'Me dumbell në duar para kofshëve, tërhiq bërrylat lart anash deri në nivel gjoksi duke ngritur supet. Ulji kontrolluar. Fokus: trapezi dhe shpatullat.' },
  { name: 'Prone Trap Raise', muscle: 'Trapez', instructions: 'Shtrihu përmbys në stol të pjerrët me dumbell të lehtë. Ngri krahët lart në vijë me trupin duke shtrënguar shpatullat dhe ulji ngadalë. Fokus: trapezi i poshtëm.' },
  { name: 'Prone T Raise', muscle: 'Trapez', instructions: 'Shtrihu përmbys në stol të pjerrët. Hapi krahët anash në formë T me gishtat e mëdhenj jashtë dhe ulji ngadalë me peshë të lehtë. Fokus: trapezi i mesëm dhe shpatulla e pasme.' },
  { name: 'Scapular Pull Up', muscle: 'Trapez', instructions: 'Varur në shufër me krahë të shtrirë, tërhiq vetëm shpatullat poshtë e prapa pa përkulur krahët dhe ktheji ngadalë. Fokus: trapezi i poshtëm.' },
  { name: 'Scapular Push Up', muscle: 'Trapez', instructions: 'Në pozicion shtytjeje me krahë të shtrirë, lëshoje gjoksin mes shpatullave dhe shtyji shpatullat larg njëra-tjetrës. Fokus: serratus dhe trapezi.' },
  { name: 'Wall Slide', muscle: 'Trapez', instructions: 'Mbështet shpinën dhe krahët pas murit. Rrëshqit krahët lart e poshtë pa i ndarë nga muri dhe me ritëm të kontrolluar. Fokus: mobiliteti dhe trapezi i poshtëm.' },
  { name: 'Band Shrug', muscle: 'Trapez', instructions: 'Qëndro mbi elastik me këmbët dhe kap skajet. Ngri supet lart kundër rezistencës dhe ule ngadalë. Fokus: trapezi, ideal për shtëpi.' },
  { name: 'Suitcase Carry', muscle: 'Trapez', instructions: 'Mbaj një peshë të rëndë me një dorë dhe ec drejt pa u anuar. Ndërro duart. Regjistro distancën ose kohën. Fokus: trapezi dhe qëndrueshmëria e bërthamës.' },
  { name: 'Isometric Shrug Hold', muscle: 'Trapez', instructions: 'Ngri supet drejt veshëve me peshë në duar dhe mbaji 20-30 sekonda pa i ulur. Regjistro sekondat. Fokus: qëndrueshmëria e trapezit të sipërm.' },
  { name: 'Barbell High Pull', muscle: 'Trapez', instructions: 'Me shufrën para kofshëve, tërhiqe lart afër trupit deri te gjoksi me bërryla lart dhe ule kontrolluar. Mos përdor peshë shumë të rëndë. Fokus: trapezi dhe fuqia.' },
  { name: 'Overhead Plate Carry', muscle: 'Trapez', instructions: 'Mbaj një pllakë me krahë të shtrirë mbi kokë dhe ec ngadalë me shpinë drejt dhe bark të shtrënguar. Regjistro distancën. Fokus: trapezi dhe stabiliteti i shpatullave.' },

  // ---------- Parakrah (20) ----------
  { name: 'Reverse Wrist Curl', muscle: 'Parakrah', instructions: 'Mbështet parakrahët mbi stol me pëllëmbë poshtë. Ngri kyçet lart dhe ulji ngadalë. Fokus: shtrirësit e parakrahut.' },
  { name: 'Dumbbell Wrist Curl', muscle: 'Parakrah', instructions: 'Mbështet një parakrah mbi kofshë me pëllëmbë lart. Përkul kyçin lart dhe ule ngadalë. Fokus: fleksorët e parakrahut njëanshëm.' },
  { name: 'Behind-the-Back Wrist Curl', muscle: 'Parakrah', instructions: 'Mbaj shufrën pas trupit me pëllëmbë nga prapa. Përkul kyçet lart dhe ulji ngadalë me shpinë drejt. Fokus: fleksorët e parakrahut dhe kapja.' },
  { name: 'Cable Wrist Curl', muscle: 'Parakrah', instructions: 'Ulu para kabllos së ulët me parakrahët mbi kofshë. Përkul kyçet lart dhe ulji ngadalë. Fokus: parakrahu me tension të vazhdueshëm.' },
  { name: 'Wrist Roller', muscle: 'Parakrah', instructions: 'Mbaj shufrën me peshë në fund të litarit para trupit. Rrotulloje duke mbledhur litarin deri lart, pastaj lëshoje ngadalë. Fokus: parakrahu dhe kapja.' },
  { name: 'Farmer\'s Hold', muscle: 'Parakrah', instructions: 'Mbaj dy pesha të rënda anash trupit pa lëvizur, me supet pas. Mbaje sa më gjatë të mundesh. Regjistro sekondat. Fokus: kapja dhe parakrahu.' },
  { name: 'Dead Hang', muscle: 'Parakrah', instructions: 'Varu në shufër me krahë të shtrirë dhe supe të ulura. Mbaje sa të mundesh pa lëkundje. Regjistro sekondat. Fokus: kapja dhe parakrahu.' },
  { name: 'Plate Pinch', muscle: 'Parakrah', instructions: 'Mbaj dy pllaka me anën e lëmuar nga jashtë, mes gishtit të madh dhe gishtave. Mbaji para trupit sa më gjatë. Regjistro sekondat. Fokus: kapja me gishta.' },
  { name: 'Towel Hang', muscle: 'Parakrah', instructions: 'Hidh një peshqir mbi shufër dhe kapi skajet. Varu pa lëvizur sa më gjatë. Regjistro sekondat. Fokus: kapja dhe parakrahu.' },
  { name: 'Reverse Cable Curl', muscle: 'Parakrah', instructions: 'Në kabllon e ulët, kap shufrën me pëllëmbë poshtë. Përkul krahët lart me bërryla pranë trupit dhe ule ngadalë. Fokus: brachioradialis dhe parakrahu.' },
  { name: 'EZ-Bar Reverse Curl', muscle: 'Parakrah', instructions: 'Kap shufrën EZ me pëllëmbë poshtë dhe bërryla pranë trupit. Përkul lart dhe ule kontrolluar. Fokus: parakrahu me më pak stres te kyçet.' },
  { name: 'Reverse Dumbbell Curl', muscle: 'Parakrah', instructions: 'Mbaj dumbellët me pëllëmbë poshtë. Përkul krahët lart pa lëkundur trupin dhe ulji ngadalë. Fokus: pjesa e sipërme e parakrahut.' },
  { name: 'Thick-Grip Curl', muscle: 'Parakrah', instructions: 'Përdor shufër ose dumbell me doreza të trasha. Përkul krahët lart me kontroll dhe ule ngadalë. Fokus: kapja dhe parakrahu.' },
  { name: 'Finger Curl', muscle: 'Parakrah', instructions: 'Mbaj shufrën me gishtat, lëshoje poshtë deri te majat e gishtave dhe mbyll duart përsëri për ta ngritur. Fokus: fleksorët e gishtave.' },
  { name: 'Hand Gripper Squeeze', muscle: 'Parakrah', instructions: 'Shtrëngo gripper-in me dorë deri sa doreza prek, mbaj një sekondë dhe lëshoje ngadalë. Ndërro duart. Fokus: forca e kapjes.' },
  { name: 'Band Wrist Extension', muscle: 'Parakrah', instructions: 'Mbështet parakrahun mbi kofshë me elastik poshtë. Ngri kyçin lart kundër elastikut dhe ule ngadalë. Fokus: shtrirësit e parakrahut dhe parandalimi i dëmtimeve.' },
  { name: 'Wrist Radial Deviation', muscle: 'Parakrah', instructions: 'Mbaj një dumbell ose çekan me pëllëmbë anash. Anoje kyçin lart dhe ule ngadalë, me peshë shumë të lehtë. Fokus: stabiliteti i kyçit.' },
  { name: 'Dumbbell Pronation-Supination', muscle: 'Parakrah', instructions: 'Mbaj një çekan ose dumbell nga njëri skaj. Rrotulloje parakrahun majtas e djathtas ngadalë, me peshë të lehtë. Fokus: rrotullimi i parakrahut.' },
  { name: 'Bottoms-Up Kettlebell Hold', muscle: 'Parakrah', instructions: 'Mbaj kettlebell-in me pjesën e rëndë lart nga doreza. Mbaje të qëndrueshëm para trupit sa më gjatë. Regjistro sekondat. Fokus: kapja dhe stabiliteti i kyçit.' },
  { name: 'Static Barbell Hold', muscle: 'Parakrah', instructions: 'Ngrije shufrën si në rack pull dhe mbaje në këmbë me shpinë drejt. Lëshoje kontrolluar. Regjistro sekondat. Fokus: kapja dhe parakrahu.' },
]
